version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: iot-rabbitmq-m7a
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks: [devnet]

  mongo:
    image: mongo:7.0
    container_name: iot-mongo-m7a
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${MONGO_USER}", "--password", "${MONGO_PASS}", "--authenticationDatabase", "admin", "--eval", "db.adminCommand({ ping: 1 })", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks: [devnet]

volumes:
  mongo_data:
  rabbitmq_data:

networks:
  devnet:
    driver: bridge

